- name: cart
  hosts: cart
  become: yes
  tasks:
  - name: enableand diable old version
    ansible.builtin.shell: dnf module disable nodejs -y ;dnf module enable nodejs:18 -y

  - name: install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: adding user
    ansible.builtin.user:
      name: roboshop

  - name: removing the directory if present and creating
    ansible.builtin.file:
      path: /app
      state: absent
  
  - name: creating a directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: download user application
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/cart.zip
      dest: /tmp

  - name: unzip or unarchive the file
    ansible.builtin.unarchive:
      src: /tmp/cart.zip
      dest: /app
      remote_src: yes

  - name: installing npm
    ansible.builtin.command: npm install 
    args:
      chdir: /app

  - name: copying service file
    ansible.builtin.copy:
      src: cart.service
      dest: /etc/systemd/system/cart.service

  - name: demon reload
    ansible.builtin.service:
      daemon-reload: true
  

  - name: start and enable user
    ansible.builtin.service:
      name: cart
      state: restarted
      enabled: yes