- name: payment
  hosts: payment
  become: yes
  tasks: 
  - name: installing python
    ansible.builtin.package:
     name: python36 gcc python3-devel
     state: present

  - name: adding user
    ansible.builtin.user:
      name: roboshop

  - name: creating a directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: downloading an application
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/payment.zip
      dest: /tmp

  - name: unzipping
    ansible.builtin.unarchive:
      src: /tmp/payment.zip
      dest: /app
      remote_src: yes
