- name: user
  hosts: user
  become: yes
  tasks:
  - name: enableand diable old version
    ansible.builtin.shell: dnf module disable nodejs -y ;dnf module enable nodejs:18 -y

  - name: install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: adding user
    ansible.builtin.user:
      name: roboshop

  - name: removing the directory if present and creating
    ansible.builtin.file:
      path: /app
      state: absent
  
  - name: creating a directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: download user application
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/user.zip
      dest: /tmp

  - name: unzip or unarchive the file
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes

  - name: installing npm
    ansible.builtin.command: npm install 
    args:
      chdir: /app

  - name: copying service file
    ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service

  - name: start and enable mongodb
    ansible.builtin.service:
      daemon-reload: true

  - name: copy mongodb
    ansible.builtin.copy:
      src: mongo.repo  
      dest: /etc/yum.repos.d/mongo.repo


  - name: install mongodb-clinet 
    ansible.builtin.package:
      name: mongodb-org-shell
      state: present 

  - name: get the categories count
    ansible.builtin.command:  mongo --host mongodb.pjdevops.online --quiet --eval 'db = db.getSiblingDB("users"); db.users.count()'
    register: user_count
    
  - name: print the count
    ansible.builtin.debug:
      msg: "user count: {{user_count}}"

  - name: load user data
    ansible.builtin.command: mongo --host mongodb.pjdevops.online < /app/schema/user.js
    when: user_count.stdout == "0" # keep double quotes

  - name: start and enable user
    ansible.builtin.service:
      name: user
      state: restarted
      enabled: yes