- name: web
  hosts: web
  become: yes
  tasks:
  - name: installing nginx
    ansible.builtin.package:
      name: nginx
      state: present

  - name: starting and enabling nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

  - name: remove html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html/*
      state: absent

  - name: creating html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html/*
      state: directory

  - name: downloading the frontend content
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/web.zip
      dest: /tmp

  - name:  files extracting
    ansible.builtin.unarchive:
     src: /tmp/web.zip
     dest: /usr/share/nginx/html
     remote_src: yes

  - name: copying the conf file
    ansible.builtin.copy:
      src: roboshop.conf
      dest: /etc/nginx/default.d/roboshop.conf 

  - name: restare the nginx
    ansible.builtin.package:
      name: nginx
      state: restarted